export const globalAirportsList = [
      { value: "SYD", label: "Sydney (SYD), Australia", region: "Oceania" },
      { value: "MEL", label: "Melbourne (MEL), Australia", region: "Oceania" },
      { value: "BNE", label: "Brisbane (BNE), Australia", region: "Oceania" },
      { value: "PER", label: "Perth (PER), Australia", region: "Oceania" },
      { value: "ADL", label: "Adelaide (ADL), Australia", region: "Oceania" },
      { value: "CBR", label: "Canberra (CBR), Australia", region: "Oceania" },
      { value: "HBA", label: "Hobart (HBA), Australia", region: "Oceania" },
      { value: "DRW", label: "Darwin (DRW), Australia", region: "Oceania" },
      { value: "CNS", label: "Cairns (CNS), Australia", region: "Oceania" },
      { value: "OOL", label: "Gold Coast (OOL), Australia", region: "Oceania" },
      { value: "AKL", label: "Auckland (AKL), New Zealand", region: "Oceania" },
      { value: "WLG", label: "Wellington (WLG), New Zealand", region: "Oceania" },
      { value: "CHC", label: "Christchurch (CHC), New Zealand", region: "Oceania" },
      { value: "ZQN", label: "Queenstown (ZQN), New Zealand", region: "Oceania" },
      { value: "DUD", label: "Dunedin (DUD), New Zealand", region: "Oceania" },

      { value: "LHR", label: "London (LHR), United Kingdom", region: "Europe" },
      { value: "LOS", label: "Lagos (LOS), Nigeria", region: "Africa" },
      { value: "JNB", label: "Johannesburg (JNB), South Africa", region: "Africa" },
      { value: "CPT", label: "Cape Town (CPT), South Africa", region: "Africa" },
      { value: "CAI", label: "Cairo (CAI), Egypt", region: "Africa" },
      { value: "DXB", label: "Dubai (DXB), UAE", region: "Middle East" },
      { value: "YYZ", label: "Toronto (YYZ), Canada", region: "North America" },
      { value: "DFW", label: "Dallas/Fort Worth (DFW), USA", region: "North America" },
      { value: "ORD", label: "Chicago (ORD), USA", region: "North America" },
      { value: "LAX", label: "Los Angeles (LAX), USA", region: "North America" },
      { value: "JFK", label: "New York (JFK), USA", region: "North America" },

      { value: "NBO", label: "Nairobi (NBO), Kenya", region: "Africa" },
      { value: "EBB", label: "Entebbe (EBB), Uganda", region: "Africa" },
      { value: "ADD", label: "Addis Ababa (ADD), Ethiopia", region: "Africa" },
      { value: "DAR", label: "Dar es Salaam (DAR), Tanzania", region: "Africa" },
      { value: "KGL", label: "Kigali (KGL), Rwanda", region: "Africa" },
      { value: "ACC", label: "Accra (ACC), Ghana", region: "Africa" },
      { value: "ABJ", label: "Abidjan (ABJ), Ivory Coast", region: "Africa" },
      { value: "DKR", label: "Dakar (DKR), Senegal", region: "Africa" }, 
      { value: "CMN", label: "Casablanca (CMN), Morocco", region: "Africa" },
      { value: "TUN", label: "Tunis (TUN), Tunisia", region: "Africa" },
      { value: "ALG", label: "Algiers (ALG), Algeria", region: "Africa" },
      { value: "TIP", label: "Tripoli (TIP), Libya", region: "Africa" }, 
      { value: "KRT", label: "Khartoum (KRT), Sudan", region: "Africa" },
      { value: "HRE", label: "Harare (HRE), Zimbabwe", region: "Africa" },
      { value: "LUN", label: "Lusaka (LUN), Zambia", region: "Africa" },
      { value: "MPM", label: "Maputo (MPM), Mozambique", region: "Africa" },
      { value: "WDH", label: "Windhoek (WDH), Namibia", region: "Africa" }, 
      { value: "GBE", label: "Gaborone (GBE), Botswana", region: "Africa" }, 
      { value: "MRU", label: "Port Louis (MRU), Mauritius", region: "Africa" }, 
      { value: "SEZ", label: "Victoria (SEZ), Seychelles", region: "Africa" }, 
      { value: "FIH", label: "Kinshasa (FIH), DR Congo", region: "Africa" }, 
      { value: "LAD", label: "Luanda (LAD), Angola", region: "Africa" }, 
      { value: "COO", label: "Cotonou (COO), Benin", region: "Africa" },
      { value: "OUA", label: "Ouagadougou (OUA), Burkina Faso", region: "Africa" },
      { value: "BJM", label: "Bujumbura (BJM), Burundi", region: "Africa" },
      { value: "NDJ", label: "N'Djamena (NDJ), Chad", region: "Africa" },
      { value: "CKY", label: "Conakry (CKY), Guinea", region: "Africa" },
      { value: "ROB", label: "Monrovia (ROB), Liberia", region: "Africa" }, 
      { value: "LLW", label: "Lilongwe (LLW), Malawi", region: "Africa" }, 
      { value: "MBA", label: "Mombasa (MBA), Kenya", region: "Africa" }, 
      { value: "JUB", label: "Juba (JUB), South Sudan", region: "Africa" },
      { value: "DUR", label: "Durban (DUR), South Africa", region: "Africa" }, 

      { value: "SIN", label: "Singapore (SIN), Singapore", region: "Southeast Asia" },
      { value: "KUL", label: "Kuala Lumpur (KUL), Malaysia", region: "Southeast Asia" },
      { value: "PEN", label: "Penang (PEN), Malaysia", region: "Southeast Asia" },
      { value: "BKK", label: "Bangkok (BKK), Thailand", region: "Southeast Asia" }, 
      { value: "DMK", label: "Bangkok (DMK), Thailand", region: "Southeast Asia" }, 
      { value: "MNL", label: "Manila (MNL), Philippines", region: "Southeast Asia" },
      { value: "CEB", label: "Cebu (CEB), Philippines", region: "Southeast Asia" },
      { value: "CGK", label: "Jakarta (CGK), Indonesia", region: "Southeast Asia" }, 
      { value: "DPS", label: "Denpasar (DPS), Indonesia", region: "Southeast Asia" }, 
      { value: "SGN", label: "Ho Chi Minh City (SGN), Vietnam", region: "Southeast Asia" },
      { value: "HAN", label: "Hanoi (HAN), Vietnam", region: "Southeast Asia" },
      { value: "PNH", label: "Phnom Penh (PNH), Cambodia", region: "Southeast Asia" },
      { value: "REP", label: "Siem Reap (REP), Cambodia", region: "Southeast Asia" },
      { value: "RGN", label: "Yangon (RGN), Myanmar", region: "Southeast Asia" },
      { value: "MDL", label: "Mandalay (MDL), Myanmar", region: "Southeast Asia" },
      { value: "VTE", label: "Vientiane (VTE), Laos", region: "Southeast Asia" },
      { value: "LPQ", label: "Luang Prabang (LPQ), Laos", region: "Southeast Asia" },
      { value: "BWN", label: "Bandar Seri Begawan (BWN), Brunei", region: "Southeast Asia" },

      { value: "DEL", label: "Delhi (DEL), India", region: "South Asia" },
      { value: "BOM", label: "Mumbai (BOM), India", region: "South Asia" },
      { value: "BLR", label: "Bengaluru (BLR), India", region: "South Asia" },
      { value: "MAA", label: "Chennai (MAA), India", region: "South Asia" },
      { value: "HYD", label: "Hyderabad (HYD), India", region: "South Asia" },
      { value: "CCU", label: "Kolkata (CCU), India", region: "South Asia" },
      { value: "AMD", label: "Ahmedabad (AMD), India", region: "South Asia" },
      { value: "PNQ", label: "Pune (PNQ), India", region: "South Asia" },
      { value: "COK", label: "Kochi (COK), India", region: "South Asia" },
      { value: "GOI", label: "Goa (GOI), India", region: "South Asia" }, 
      { value: "IXC", label: "Chandigarh (IXC), India", region: "South Asia" },


      { value: "CDG", label: "Paris (CDG), France", region: "Europe" },
      { value: "AMS", label: "Amsterdam (AMS), Netherlands", region: "Europe" },
      { value: "FRA", label: "Frankfurt (FRA), Germany", region: "Europe" },
      { value: "IST", label: "Istanbul (IST), Turkey", region: "Europe/Asia" },
      { value: "DOH", label: "Doha (DOH), Qatar", region: "Middle East" },
      { value: "AUH", label: "Abu Dhabi (AUH), UAE", region: "Middle East" },
      { value: "PEK", label: "Beijing (PEK), China", region: "East Asia" }, 
      { value: "PKX", label: "Beijing (PKX), China", region: "East Asia" }, 
      { value: "PVG", label: "Shanghai (PVG), China", region: "East Asia" }, 
      { value: "ICN", label: "Seoul (ICN), South Korea", region: "East Asia" }, 
      { value: "NRT", label: "Tokyo (NRT), Japan", region: "East Asia" }, 
      { value: "HND", label: "Tokyo (HND), Japan", region: "East Asia" }, 
    ];

    export const originAirportCodes = [
      "SYD", "MEL", "BNE", "PER", "ADL", "CBR", "HBA", "DRW", "CNS", "OOL", 
      "AKL", "WLG", "CHC", "ZQN", "DUD", 
      "LHR", "LOS", "JNB", "CPT", "CAI", "DXB", 
      "YYZ", "DFW", "ORD", "LAX", "JFK"
    ];

    export const destinationAirportCodes = [
      
      ...originAirportCodes, 
      
      
      "NBO", "EBB", "ADD", "DAR", "KGL", "ACC", "ABJ", "DKR", "CMN", "TUN", "ALG", "TIP", "KRT", "HRE", "LUN", "MPM", "WDH", "GBE", "MRU", "SEZ", "FIH", "LAD", "COO", "OUA", "BJM", "NDJ", "CKY", "ROB", "LLW", "MBA", "JUB", "DUR",

      
      "SIN", 
      "KUL", "PEN", 
      "BKK", "HKT", 
      "MNL", "CEB", 
      "CGK", "DPS", 
      "SGN", "HAN", 
      "PNH", "REP", 
      "RGN", 
      "VTE", 
      "BWN", 

      
      "DEL", "BOM", "BLR", "MAA", "HYD", "CCU", "AMD", "PNQ", "COK", "GOI", "IXC",
      
      
      "CDG", "AMS", "FRA", "IST", "DOH", "AUH", "PEK", "PKX", "PVG", "ICN", "NRT", "HND"
    ];